# Generated by Django 4.0.6 on 2022-11-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisment_client', '0002_alter_advertisement_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
