# Generated by Django 4.0.6 on 2022-11-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisment_client', '0003_alter_advertisement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.CharField(max_length=50),
        ),
    ]
