# Generated by Django 4.0.6 on 2022-11-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisment_client', '0004_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
